# Generated by Django 3.2.5 on 2021-07-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(max_length=255)),
                ('username2', models.CharField(max_length=255)),
                ('current_turn', models.CharField(max_length=255)),
                ('player1_cards', models.TextField(null=True)),
                ('player2_cards', models.TextField(null=True)),
                ('roomid', models.CharField(max_length=255)),
                ('total_cards', models.TextField(null=True)),
                ('used_cards', models.TextField(null=True)),
                ('remaining_cards', models.TextField(null=True)),
            ],
        ),
    ]
